application:
  port: 8080
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "mypage"
  socket: ""
  require_ssl: true
auth0_settings:
  rsa_n: ""
  rsa_e: ""
  audience: ""
  domain: ""