application:
  port: 8080
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "mypage"
  socket: ""
  require_ssl: false
auth0_settings:
  audience: ""
  issuer: ""
  domain: ""
