name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: "build"
        run: "docker build -t asia-northeast1-docker.pkg.dev/$PROJECT_NAME/$IMAGE_NAME:latest ."

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.REGISTRY_USER_SECRET }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: "gcloud auth configure-docker asia-northeast1-docker.pkg.dev"

      - name: "Push image"
        run: "docker push asia-northeast1-docker.pkg.dev/$PROJECT_NAME/$IMAGE_NAME:latest"
